import { v4 } from "uuid";

export function classNames(...classes: string[]) {
  return classes.filter(Boolean).join(" ");
}

export const people = [
  {
    id: "1",
    name: "Maths",
    title: "Frontend Developer",
    createdDate: "25th August",
    role: "User",
    email: "virinchi.msk83@gmail.com",
  },
  {
    id: "2",
    name: "Science ",
    title: "Founder",
    createdDate: "15th August",
    role: "Admin",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },
  {
    id: v4(),
    name: `geo-${v4()}`,
    title: "Frondend Devolper",
    createdDate: "25th september",
    role: "user",
    email: "rohith@krk.com",
  },

  // More people...
];
